### PR TITLE
New test api views

### PR DESCRIPTION
**Pull request by CecileSun**

### CODE REVIEW

**Comment by tonylampada** [comment]
Test PASSed.
Refer to this link for build results: http://jenkins.freedomsponsors.org/job/FreedomSponsors/372/

**Comment by tonylampada** [comment]
Thanks. Next time, no need for leaving the old code commented!

**Comment by tonylampada** [comment]
Look, your code is in production. ;)
https://freedomsponsors.org/api/project/10000

Before, it would crash and I would get an error email

**Comment by CecileSun** [comment]
Yeah! Thank you so much :p

**Pull request merged**
